"""rename_purchase_tickets_table

Revision ID: 0002
Revises: 0001
Create Date: 2026-08-30 18:18:22.786566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_payment_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('payments_count', sa.Integer(), nullable=False),
    sa.Column('tickets_count', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_payment_activity_event_id'), 'event_payment_activity', ['event_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_payment_activity_event_id'), table_name='event_payment_activity')
    op.drop_table('event_payment_activity')
    # ### end Alembic commands ###
